repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.0
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
        additional_dependencies:
          - alembic>=1.16,<2.0
          - fastapi>=0.116,<1.0
          - httpx2>=2.12,<3.0
          - pydantic>=2.11,<3.0
          - pytest>=8.4,<9.0
          - sqlalchemy>=2.0,<3.0
