apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../namespace.yaml
  - ../control-plane.yaml
  - ../observability.yaml
  - api-secrets.yaml
patches:
  - path: control-plane-env-patch.yaml
  - path: alertmanager-volume-patch.yaml
  - path: alertmanager-config-patch.yaml
