"""Shared scalar bounds for the ITBench V5 provider/runtime contract."""

V5_TARGET_MAX_LENGTH = 16
V5_TARGETS_MAX_ITEMS = 3
V5_OPERATION_MAX_LENGTH = 64
V5_RATIONALE_MAX_LENGTH = 300
V5_STOP_REASON_MAX_LENGTH = 128
V5_SUBMIT_MIN_TARGETS = 1


__all__ = [
    "V5_OPERATION_MAX_LENGTH",
    "V5_RATIONALE_MAX_LENGTH",
    "V5_STOP_REASON_MAX_LENGTH",
    "V5_SUBMIT_MIN_TARGETS",
    "V5_TARGETS_MAX_ITEMS",
    "V5_TARGET_MAX_LENGTH",
]
